import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './nav.js'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div>
					<header>
						<h1>Next.js study</h1>
					</header>
					<hr />
					<div className='container'>
						<Nav />
						<hr />
						<section className='contents'>{children}</section>
						<hr />
					</div>
					<footer>Copyright</footer>
				</div>
			</body>
		</html>
	)
}
